language: objective-c
osx_image: xcode10.3

env:
  matrix:
      - DESTINATION="OS=10.0,name=iPhone 7 Plus"
      - DESTINATION="platform=iOS Simulator,name=iPhone X"

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - rake test:framework DESTINATION="$DESTINATION"
  - rake test:app DESTINATION="$DESTINATION"
  - pod lib lint --quick
